# Generated by Django 3.0.8 on 2020-07-23 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('birthdate', models.DateField(blank=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('sexe', models.CharField(blank=True, max_length=200)),
                ('nationalite', models.CharField(blank=True, max_length=200)),
                ('region_origine', models.CharField(blank=True, max_length=200)),
                ('departement_origine', models.CharField(blank=True, max_length=200)),
                ('filiere_choisie', models.CharField(blank=True, max_length=200)),
                ('annee_probatoire', models.IntegerField()),
                ('mention_probatoire', models.CharField(blank=True, max_length=200)),
                ('annee_bac', models.IntegerField(blank=True)),
                ('mention_bac', models.CharField(blank=True, max_length=200)),
                ('photocopie_bac', models.CharField(blank=True, max_length=200)),
                ('photocopie_releve_note_bac', models.CharField(blank=True, max_length=200)),
                ('photocopie_releve_note_probatoire', models.CharField(blank=True, max_length=200)),
                ('recu_paiement', models.CharField(blank=True, max_length=200)),
                ('photocopie_acte_naissance', models.CharField(blank=True, max_length=200)),
                ('certificat_medical', models.CharField(blank=True, max_length=200)),
                ('photo_4x4', models.CharField(blank=True, max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
