# Generated by Django 3.0.8 on 2020-07-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='birthdate',
            new_name='datebirth',
        ),
    ]
