# Generated by Django 3.0.8 on 2020-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200723_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='datebirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
