# Generated by Django 3.0.8 on 2020-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200723_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='datebirth',
            new_name='date_naissance',
        ),
        migrations.RenameField(
            model_name='dossier',
            old_name='full_name',
            new_name='nom_complet',
        ),
        migrations.AlterField(
            model_name='dossier',
            name='annee_bac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='certificat_medical',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='departement_origine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='filiere_choisie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='mention_bac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='mention_probatoire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='nationalite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photo_4x4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photocopie_acte_naissance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photocopie_bac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photocopie_releve_note_bac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photocopie_releve_note_probatoire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='recu_paiement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='region_origine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='sexe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
