# Generated by Django 3.0.8 on 2020-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200723_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='annee_probatoire',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
