# Generated by Django 3.0.8 on 2020-07-23 14:49

from django.db import migrations, models
import registration.utils


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200723_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='code',
            field=models.CharField(default=registration.utils.get_random_string, max_length=200),
        ),
    ]
