# Generated by Django 3.0.8 on 2020-07-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200723_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='centre_examen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
