# Generated by Django 3.0.8 on 2020-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_dossier_centre_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='delete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
