# Generated by Django 3.0.8 on 2020-07-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_dossier_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='certificat_medical',
            field=models.ImageField(blank=True, null=True, upload_to='dossier/'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photo_4x4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photocopie_acte_naissance',
            field=models.ImageField(blank=True, null=True, upload_to='dossier/'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photocopie_bac',
            field=models.ImageField(blank=True, null=True, upload_to='dossier/'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photocopie_releve_note_bac',
            field=models.ImageField(blank=True, null=True, upload_to='dossier/'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photocopie_releve_note_probatoire',
            field=models.ImageField(blank=True, null=True, upload_to='dossier/'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='recu_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='dossier/'),
        ),
    ]
